### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by dalcantara** [steveswinsburg/oracle12c-docker#4]
After running through the steps listed in the documentation, I was able to verify that the DB container was running successfully.  However, trying to connect via SQL Developer gave me authentication errors (invalid username/password).  I tried connecting using:
username: oracle pwd: password & username: 54321 pwd: password.  However, both attempts were rejected with an "invalid credentials" message.

**Comment by steveswinsburg** [comment]
Hi, sorry for the late reply, sys/password is what you are after.
